name: GitHub CI

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: flake8
      run: pip install flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'CI workflow'
    - name: black
      uses: psf/black@stable